services:
  - type: web
    name: intellidocs-api
    runtime: python
    pythonVersion: 3.11
    buildCommand: |
      pip install --upgrade pip setuptools wheel build
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        value: your-api-key-here
